
city_name_translate = [
    {"name_en": "Akko", "name_hb": "עכו"},
    {"name_en": "Almagor", "name_hb": "אלמגור"},
    {"name_en": "Almog", "name_hb": "אלמוג"},
    {"name_en": "Amazia", "name_hb": "אמאסיה"},
    {"name_en": "Amiad", "name_hb": "לחיות"},
    {"name_en": "Amirim", "name_hb": "אמירים"},
    {"name_en": "Arad", "name_hb": "ערד"},
    {"name_en": "Arbel", "name_hb": "ארבל"},
    {"name_en": "Arrabe", "name_hb": "ערבי"},
    {"name_en": "Ashdod", "name_hb": "אשדוד"},
    {"name_en": "Ashdot Yaakov Ihud", "name_hb": "אשדות יעקב איחוד"},
    {"name_en": "Ashkelon", "name_hb": "אשקלון"},
    {"name_en": "Bat Yam", "name_hb": "בת ים"},
    {"name_en": "Beit Oren", "name_hb": "בית אורן"},
    {"name_en": "Beit Hillel", "name_hb": "בית הלל"},
    {"name_en": "Beer Yaakov", "name_hb": "באר יעקב"},
    {"name_en": "Beer Sheva", "name_hb": "באר שבע"},
    {"name_en": "Vered HaGalil", "name_hb": "ורד הגליל"},
    {"name_en": "Bethlehem", "name_hb": "בית לחם"},
    {"name_en": "Bethlehem, Galilee", "name_hb": "בית לחם הגלילית"},
    {"name_en": "Heirzliya", "name_hb": "גיירצליה"},
    {"name_en": "Gesher HaZiv", "name_hb": "גשר הזיו"},
    {"name_en": "Ginosar", "name_hb": "גינוסר"},
    {"name_en": "Golan Heights", "name_hb": "רמת הגולן"},
    {"name_en": "Gonen", "name_hb": "גונן"},
    {"name_en": "Degania Beth", "name_hb": "דף דגניה"},
    {"name_en": "Dimona", "name_hb": "דימונה"},
    {"name_en": "Dor", "name_hb": "דור"},
    {"name_en": "Yehud", "name_hb": "אהוד"},
    {"name_en": "Zichron Yaakov", "name_hb": "זכרון יעקב"},
    {"name_en": "Iwe-Yehuda", "name_hb": "איב יהודה"},
    {"name_en": "Jerusalem", "name_hb": "ירושלים"},
    {"name_en": "Jerusalem", "name_hb": "ירושלים - מזרח"},
    {"name_en": "Jerusalem", "name_hb": " ירושלים - מרכז"},
    {"name_en": "Jerusalem", "name_hb": "ירושלים - צפון"},
    {"name_en": "Yesud Gamaala", "name_hb": "יסוד גמאלה"},
    {"name_en": "Katzrin", "name_hb": "קטרין"},
    {"name_en": "Caesarea", "name_hb": "קיסריה"},
    {"name_en": "Kinneret", "name_hb": "כנרת"},
    {"name_en": "Kiryat Shmona", "name_hb": "קריית שמונה"},
    {"name_en": "Kfar Bloom", "name_hb": "כפר בלום"},
    {"name_en": "Kfar Giladi", "name_hb": "כפר גלעדי"},
    {"name_en": "Kfar Yehetzkel", "name_hb": "כפר אחקל"},
    {"name_en": "Kfar Kish", "name_hb": "כפר קיש"},
    {"name_en": "Kfar Adumim", "name_hb": "כפר אדומים"},
    {"name_en": "Livnim", "name_hb": "ליבנים"},
    {"name_en": "Maagan", "name_hb": "מעגן"},
    {"name_en": "Maale Hachamisha", "name_hb": "מעלה החמישה"},
    {"name_en": "Maalot-Tarshiha", "name_hb": "מעלות-תרשיחא"},
    {"name_en": "Majdal Shams", "name_hb": "מג'דל-שמס"},
    {"name_en": "Mazkeret Batya", "name_hb": "מזכרת בתיה"},
    {"name_en": "Malkiya", "name_hb": "מלכיה"},
    {"name_en": "Mashabey Sade", "name_hb": "מאשבי סאד"},
    {"name_en": "Menara", "name_hb": "מנרה"},
    {"name_en": "Metula", "name_hb": "מטולה"},
    {"name_en": "Misra", "name_hb": "מזרע"},
    {"name_en": "Mitzpe Ramon", "name_hb": "מצפה רמון"},
    {"name_en": "Moran", "name_hb": "מורן"},
    {"name_en": "Moshav Neve", "name_hb": "מושב נווה"},
    {"name_en": "Nahariya", "name_hb": "נהריה"},
    {"name_en": "Nazareth", "name_hb": "נצרת"},
    {"name_en": "Nachsholim", "name_hb": "נחשלים"},
    {"name_en": "Nazareth Illit", "name_hb": "נצרת-עילית"},
    {"name_en": "Neve Zohar", "name_hb": "נווה זוהר"},
    {"name_en": "Neve-Ilan", "name_hb": "נווה-אילן"},
    {"name_en": "Neot HaKikar", "name_hb": "נאות הכיכר"},
    {"name_en": "Nes Ammin", "name_hb": "נס אמין"},
    {"name_en": "Netanya", "name_hb": "נתניה"},
    {"name_en": "Netiv HaShayara", "name_hb": "נתיב-השעירה"},
    {"name_en": "Niot Golan", "name_hb": "ניוות-גולן"},
    {"name_en": "Nir-David", "name_hb": "ניר-דוד"},
    {"name_en": "Ra'anana", "name_hb": "רעננה"},
    {"name_en": "Ramat Gan", "name_hb": "רמת-גן"},
    {"name_en": "Ramot", "name_hb": "המסגרת"},
    {"name_en": "Ramot Naftali", "name_hb": "רמות-נפתלי"},
    {"name_en": "Rehovot", "name_hb": "רחובות"},
    {"name_en": "Rosh Pinna", "name_hb": "ראש פינה"},
    {"name_en": "Tiberias", "name_hb": "טבריה"},
    {"name_en": "Tel Aviv", "name_hb": "תל אביב"},
    {"name_en": "Had Nes", "name_hb": "היה נס"},
    {"name_en": "Haifa", "name_hb": "חיפה"},
    {"name_en": "Hamat Heyder", "name_hb": "חמת היידר"},
    {"name_en": "Harel", "name_hb": "הראל"},
    {"name_en": "Khatseva", "name_hb": "חצ'בה"},
    {"name_en": "Huqoq", "name_hb": "חוקוק"},
    {"name_en": "Tsova", "name_hb": "קובה"},
    {"name_en": "Tsukim", "name_hb": "אני צווחת"},
    {"name_en": "Safed", "name_hb": "צפת"},
    {"name_en": "Sha'ar HaGolan", "name_hb": "שער הגולן"},
    {"name_en": "Shavei Zion", "name_hb": "שבי-ציון"},
    {"name_en": "Sharona", "name_hb": "שרונה"},
    {"name_en": "She'ar Yishuv", "name_hb": "שאר יישוב"},
    {"name_en": "Shefayim", "name_hb": "אני מרפא"},
    {"name_en": "Shoresh", "name_hb": "שורש"},
    {"name_en": "Eilat", "name_hb": "אילת"},
    {"name_en": "Eilon", "name_hb": "אילון"},
    {"name_en": "Ein Bokek", "name_hb": "עין בוקק"},
    {"name_en": "Ein Gev", "name_hb": "עין-גב"},
    {"name_en": "Ein Gedi", "name_hb": "עין גדי"},
    {"name_en": "Ein Tamar", "name_hb": "עין תמר"},
    {"name_en": "Ein Had", "name_hb": "עין חד"},
    {"name_en": "Ein Herod", "name_hb": "עין-הורדוס"},
    {"name_en": "Yuval", "name_hb": "יובל"},
    {"name_en": "Yad HaShmona", "name_hb": "יד השמונה"},
    {"name_en": "Jaffa", "name_hb": "יפו"},
]
